name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp libavif-bin
          npm install -g netlify-cli
      
      # Option 1: Use Netlify CLI directly with explicit site ID
      - name: Deploy to Netlify
        run: |
          npx netlify deploy --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir="."
        
      # Uncomment this section if you still need to run your deploy script for image processing
      # - name: Process images (if needed)
      #   run: |
      #     chmod +x ./deploy.sh
      #     ./deploy.sh --skip-deploy
          
      - name: Output deployment URL
        run: echo "Site deployed to Netlify!" 